seed: 0
max_steps: 1_000_000

encoder:
  encoder_dim: 256
  num_encoder_layers: 1

world_model:
  mlp_dim: 256
  latent_dim: 256
  value_dropout: 0
  num_value_nets: 5
  num_bins: 101
  symlog_min: -10
  symlog_max: 10
  simnorm_dim: 8
  learning_rate: 3e-4
  encoder_learning_rate: 1e-4
  tabulate: False
  dtype: bfloat16

tdmpc2:
  # Planning
  mpc: False
  horizon: 1
  mppi_iterations: 6
  population_size: 512
  policy_prior_samples: 24
  num_elites: 64
  min_plan_std: 0.05
  max_plan_std: 2
  temperature: 0.5
  # Optimization
  batch_size: 256
  discount: 0.99
  rho: 0
  consistency_coef: 0
  reward_coef: 0
  value_coef: 0.1
  entropy_coef: 1e-4
  tau: 0.01